Article_Features/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.listArticles, name='list-articles'),
    path('create-article/', views.createArticle, name='create-article'),
    path('<int:id>/', views.articless, name='article'),
    path('search/', views.searcharticle, name='search'),
    path('manage/', views.managearticles, name='manage-articles'),
    path('delete/<int:id>/', views.deletearticle, name='delete-article'),
    path('edit/<int:id>/', views.editarticle, name='edit-article')
]

bmi/urls.py
from django.urls import include, path

from . import views

app_name = 'bmi'

urlpatterns = [
    path('', views.BMIHome, name='BMIHome'),
    path('submit/', views.submit, name='submit')
]

tk1_e06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('bmi/', include('bmi.urls')),
    path('calories-cal/', include('Calories_Calc.urls')),
    path('to-do-list/', include('ToDoList_Features.urls', namespace='to-do-list')),
    path('articles/', include('Article_Features.urls', namespace='articles')),
    path('bmrcalculator/', include('bmrcalculator.urls')),
    path('user/', include('user.urls', namespace='user')),
]

Article_Features/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField
from django.conf import settings


import datetime
# Create your models here.

class Articles(models.Model):
    tittle = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = RichTextField(blank=True, null=True)
    image = CloudinaryField('image')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)


    def __str__(self):
        return '{}'.format(self.tittle)

Article_Features/forms.py
from django import forms
from .models import Articles

class article(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            'tittle',
            'author',
            'description',
            'image',
        ]

        labels = {
            'tittle': 'Tittle',
            'author': 'Author',
            'description' : 'Description',
            'image' : 'Image'
        }

        widgets = {
            'tittle' : forms.TextInput(attrs= {'class' : 'form-control', 'style' : 'background-color: #E4E4E4;', 'placeholder' : 'ex: How to increase...',}),
            'author' : forms.Select(attrs= {'class' : 'form-control', 'style' : 'background-color: #E4E4E4;'}),
            'description' : forms.Textarea(attrs= {'class' : 'form-control',}),
            'image' : forms.FileInput(attrs= {'class' : 'form-control-file',}),
        }

Article_Features/views.py
from django.forms import model_to_dict
from django.shortcuts import render, redirect

# Create your views here.

from django import forms
from django.http import HttpResponse, JsonResponse
from cloudinary.forms import cl_init_js_callbacks
from django.template.loader import render_to_string

from .models import Articles
from .forms import article
from django.contrib.auth.models import User

def createArticle(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user.username)
        test = article(initial={'author' : user.id})
        context = { 'backend_form' : test,}
        if request.method == 'POST':
            form = article(request.POST, request.FILES)
            context['posted'] = form.instance
            if form.is_valid():
                form.save()
                data = {'boolean' : True}
                return JsonResponse(data, safe=False)
            else:
                data = {'boolean' : False}
                return JsonResponse(data, safe=False)
        else:
            return render(request, 'Article_Features/create-article.html', context)
    else:
        return redirect('articles:list-articles')

def listArticles(request):
    articles = Articles.objects.all()
    context = {'articles' : articles,
               'type' : 'list'}
    return render(request, 'Article_Features/list-articles.html', context)

def articless(request, id):
    arc = Articles.objects.get(id=id)
    context = {'article' : arc}
    return render(request, 'Article_Features/article.html', context)

def searcharticle(request):
    arg = request.GET['q']
    data = {'size' : 0, 'items' : []}
    datas = Articles.objects.filter(tittle__istartswith=arg)
    data['size'] = Articles.objects.filter(tittle__istartswith=arg).count()
    item = data['items']
    for d in datas:

        y = {'tittle' : d.tittle,
               'author' : d.author.get_full_name(),
               'image' : d.image.url,
                'id' : d.id,
              }
        item.append(y)
    return JsonResponse(data, safe=False)

def managearticles(request):
    if request.user.is_authenticated:
        articles = Articles.objects.filter(author=request.user)
        context = {'articles': articles,
                   'type' : 'manage'}
        return render(request, 'Article_Features/manage-articles.html', context)
    else:
        return redirect('articles:list-articles')

def deletearticle(request, id):
    if request.user.is_authenticated:
        Article = Articles.objects.get(id=id)
        data = {}
        if request.method == 'GET':
            Article.delete()
            data['boolean'] = True
            articles = Articles.objects.filter(author=request.user)
            context = {'articles': articles}
            data['html'] = render_to_string('Article_Features/card_articles.html', context, request)
        return JsonResponse(data, safe=False)
    else:
        return redirect('articles:manage-articles')

def editarticle(request, id):
    if request.user.is_authenticated:
        Article = Articles.objects.get(id=id)
        data = dict()
        if request.method == 'POST':
            form = article(request.POST, request.FILES, instance=Article)
            if form.is_valid():
                form.save()
                data['boolean'] = True
                articles = Articles.objects.filter(author=request.user)
                arc = {'articles': articles}
                data['html'] = render_to_string('Article_Features/card_articles.html', arc, request)
        else:
            form = article(instance=Article)
        context = {'backend_form' : form}
        data['html_form'] = render_to_string('Article_Features/modal-edit-article.html', context, request=request)
        return JsonResponse(data, safe=False)
    else:
        return redirect('articles:manage-articles')

Article_Features/templates/Article_Features/article.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>{{ article.tittle }}</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
  <div class="container">
      <div class="head">
          <h3 class="tittle-article">{{ article.tittle }}</h3>
          <p class="author-artice">Author: {{ article.author }}</p>
          <p class="date-article">{{ article.create }}</p>
      </div>
      <div>
          <img src="{{ article.image.url }}" class="picture-article">
      </div>
      <div>
          {{ article.description|safe }}
      </div>
  </div>
{% endblock content %}

Article_Features/templates/Article_Features/card_articles.html
{% if articles.count != 0 %}
    <div class="card-deck">
        {% for article in articles %}
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{{ article.image.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'articles:article' article.id %}" class="font-tittle">{{ article.tittle }}</a></h5>
                        <i class="fas fa-user"><small style="margin-left: 5px; font-family: Rubik,sans-serif">{{ article.author.get_full_name }}</small></i><br>
                        <i class="fas fa-calendar-day"><small style="margin-left: 5px; font-family: Rubik,sans-serif">{{ article.create }}</small></i>
                    </div>
                    {% if user.is_authenticated and type == 'manage'%}
                        <button class="edit-article btn btn-primary" type="submit" data-url="{% url 'articles:edit-article' article.id %}">edit</button>
                        <button class="delete-article btn btn-danger" type="submit" data-url="{% url 'articles:delete-article' article.id %}">delete</button>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div style="text-align: center">
        <h4>You haven't added any articles yet</h4>
    </div>
{% endif %}
{% if user.is_authenticated%}
    <div style="text-align: center; margin: 10%">
        <a href="{% url 'articles:create-article' %}"><i class="fas fa-plus-circle" id="add"></i></a>
    </div>
{% elif user.is_authenticated and articles.count == 0%}
    <div style="text-align: center">
        <h4>You haven't added any articles yet</h4>
        <h4>Click icon + to add article</h4>
    </div>
{% endif %}

Article_Features/templates/Article_Features/create-article.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Create Article</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    {% load cloudinary %}
    <div class="container">
        <h1 class="tittle">Create article</h1>
        <form method="POST" class="form-group" enctype="multipart/form-data" id="create-submission">
            {% csrf_token %}
            {{ backend_form.media }}
            <div class="form-group row">
                <label for="{{ backend_form.tittle.id_for_label }}" class="col-sm-2 col-form-label font">Tittle:</label>
                    <div class="col-sm-10">
                        {{ backend_form.tittle }}
                    </div>
            </div>
            <div class="form-group row" style="display: none">
                <label for="{{ backend_form.author.id_for_label }}" class="col-sm-2 col-form-label font">Author:</label>
                    <div class="col-sm-10">
                        {{ backend_form.author }}
                    </div>
            </div>
            <div class="form-group row">
                <label for="{{ backend_form.description.id_for_label }}" class="col-sm-2 col-form-label font">Description:</label>
                    <div class="col-sm-10">
                        {{ backend_form.description }}
                    </div>

            </div>
            <div class="form-group row">
                <label for="{{ backend_form.image.id_for_label }}" class="col-sm-2 col-form-label font">Image:</label>
                    <div class="col-sm-10">
                        {{ backend_form.image }}
                    </div>
            </div>
            <div style="text-align: center">
                <button class= "btn btn-primary" type="submit" style="background-image: linear-gradient(#EC4057, #F57434); border-color: #EC4057">Submit</button>
            </div>
        </form>
    </div>
    <script src="{% static 'js/create-article.js' %}"></script>
{% endblock content %}

Article_Features/templates/Article_Features/list-articles.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Health Articles</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock meta %}

{% block content %}
  <div class="container">
        <h1 class="tittle">Health Articles</h1>
        <div class="wrapper" style="margin-bottom: 20px">
            <div class="search-input">
                <input type="text" id="keyword" placeholder="Insert your article tittle">
                <div class="autocom-box">
                </div>
                <div class="icon"><i class="fas fa-search"></i></div>
            </div>
        </div>
        {% include 'Article_Features/card_articles.html' %}
    </div>
    <script src="{% static 'js/list-articles.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock content %}

Article_Features/templates/Article_Features/manage-articles.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Health Articles</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    <div class="container">
        <h1 class="tittle">Health Articles</h1>
        <div class="wrapper" style="margin-bottom: 20px">
            <div class="search-input">
                <input type="text" id="keyword" placeholder="Insert your article tittle">
                <div class="autocom-box">
                </div>
                <div class="icon"><i class="fas fa-search"></i></div>
            </div>
        </div>
        <div class="con">
            {% include 'Article_Features/card_articles.html' %}
        </div>
    </div>
     <div class="modal fade bd-example-modal-lg" id="modal-book">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <script src="{% static 'js/manage-article.js' %}"></script>
{% endblock content %}

Article_Features/templates/Article_Features/modal-create-article.html
<div class="modal-body">
        {% csrf_token %}
        {{ backend_form.media }}
        <div class="form-group">
            <label for="{{ backend_form.tittle.id_for_label }}" class="col-form-label">Tittle:</label>
            {{ backend_form.tittle }}
        </div>
        <div class="form-group" style="display: none">
            <label for="{{ backend_form.author.id_for_label }}" class="col-form-label">Author:</label>
            {{ backend_form.author }}
        </div>
        <div class="form-group">
            <label for="{{ backend_form.description.id_for_label }}" class="col-form-label">Description:</label>
            {{ backend_form.description }}
        </div>
        <div class="form-group">
            <label for="{{ backend_form.image.id_for_label }}" class="col-form-label">Image:</label>
            {{ backend_form.image }}
        </div>
</div>

Article_Features/templates/Article_Features/modal-edit-article.html
<div class="modal-header">
    <h5 class="modal-title">Edit Article</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form method="post" class="edit-article" action="{% url 'articles:edit-article' backend_form.instance.id%}">
    {% include 'Article_Features/modal-create-article.html' %}
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send message</button>
    </div>
</form>