Article_Features/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.listArticles, name='list-articles'),
    path('create-article/', views.createArticle, name='create-article'),
    path('<int:id>/', views.articless, name='article'),
    path('search/', views.searcharticle, name='search'),
    path('manage/', views.managearticles, name='manage-articles'),
    path('delete/<int:id>/', views.deletearticle, name='delete-article'),
    path('edit/<int:id>/', views.editarticle, name='edit-article')
]

ToDoList_Features/urls.py
from django.urls import path

from . import views
from .views import TaskList

app_name = 'to-do-list'

urlpatterns = [
    path('', TaskList.as_view(), name='task_list'),
    path('<str:id>/completed/', views.TaskComplete, name='task_list_complete'),
    path('<str:id>/delete/', views.TaskDelete, name='task_list_delete'),
]

bmi/urls.py
from django.urls import include, path

from . import views

app_name = 'bmi'

urlpatterns = [
    path('', views.BMIHome, name='BMIHome'),
    path('submit/', views.submit, name='submit')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('mail/', views.mail, name='mail'),
    path('searchusername/', views.searchusername, name='serarchusername'),
]

tk1_e06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('bmi/', include('bmi.urls')),
    path('calories-cal/', include('Calories_Calc.urls')),
    path('to-do-list/', include('ToDoList_Features.urls', namespace='to-do-list')),
    path('articles/', include('Article_Features.urls', namespace='articles')),
    path('bmrcalculator/', include('bmrcalculator.urls')),
    path('user/', include('user.urls', namespace='user')),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LogIn, name='login'),
    path('logout/', views.LogOut, name='logout'),
    path('signup/', views.SignUp, name='signup'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/992432344a.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <div>
        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars"></i>
            </label>

            <label class="logo">HealthLab</label>
            <ul class="menu">
                <li class="menu-item"><a href="{% url 'main:home' %}">Home</a></li>
                <li class="menu-item"><a href="{% url 'main:aboutus' %}">About Us</a></li>
                <li class="menu-item"><a>Calculator</a>
                    <ul class="dropdown">
                        <li class="sub-menu-item"><a href="{% url 'bmi:BMIHome' %}">BMI Calculator</a></li>
                        <li class="sub-menu-item"><a href="/bmrcalculator/">BMR Calculator</a></li>
                        <li class="sub-menu-item"><a href="/calories-cal/">Calories Calculator</a></li>
                    </ul>
                </li>
                <li class="menu-item"><a>Health Articles</a>
                    <ul class="dropdown">
                        <li class="sub-menu-item"><a href="{% url 'articles:list-articles' %}">List Articles</a></li>
                        {% if user.is_authenticated %}
                            <li class="sub-menu-item"><a href="{% url 'articles:manage-articles' %}">Manage Articles</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="menu-item"><a href="{% url 'to-do-list:task_list' %}">To-Do List</a></li>

                {% if user.is_authenticated and request.user.get_short_name != '' %}
                <li class="menu-item">HELLO, {{request.user.get_short_name}}</li>
                <li class="menu-item"><a href="{% url 'user:logout' %}">Log out</a></li>
                {% elif user.is_authenticated and request.user.get_short_name == '' %}
                    <li class="menu-item">HELLO, {{request.user}}</li>
                    <li class="menu-item"><a href="{% url 'user:logout' %}">Log out</a></li>
                {% else %}
                <li class="menu-item"><a href="{% url 'user:login' %}">Log in</a></li>
                <li class="menu-item"><a href="{% url 'user:signup' %}">Sign up</a></li>
            
                {% endif %}
            </ul>
        </nav>
    </div>
  {% block content %}
  {% endblock content %}
  <div class="jumbotron" style="background-color: #111111; padding-top: 8%; margin:auto; color: white">
    <div class="container" style="background-color: #504849; padding: 3%">
        <div class="row">
            <div class="col-md-6" >
                <h4 class="font-weight-bold">SUBSCRIBE FOR MORE</h4>
                <h5>Send your mail to get more information about your health in these current pandemic situation</h5>
            </div>
            <div class="col-md-6" style="padding-top: 2%">
                <form method="post" action="{% url "main:mail" %}" class="row" id="email-submission">
                    {% csrf_token %}
                    <div class="form-group col-xl-9">
                      <input type="email" name="mail" class="form-control" id="email" placeholder="name@example.com">
                    </div>
                    <div class="col-xl-3" id="submit">
                        <button class= "btn btn-primary" type="submit" name="nextURL" value="{{ request.path }}" style="background-image: linear-gradient(#EC4057, #F57434); border-color: #EC4057" >Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row" style="padding-top: 3%">
            <div class="col-sm-6 font-copyright">
                <h6>Copyright  2020 All rights reserved | TK1 PPW E06</h6>
            </div>
            <div class="col-sm-6 icon-size">
                <span class="fab fa-facebook" style="padding: 0 2%"></span>
                <span class="fab fa-instagram" style="padding: 0 2%"></span>
                <span class="fab fa-twitter" style="padding: 0 2%"></span>
                <span class="fab fa-youtube" style="padding: 0 2%"></span>
            </div>
        </div>
    </div>
  </div>
    <script src="{% static 'js/style.js' %}"></script>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

      <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
      -->
</body>
</html>